#file: noinspection SpellCheckingInspection
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    depends_on:
      - db
      - pocketbase
    networks:
      - sanctum_internal
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: metrics
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5400:5432"
    networks:
      - sanctum_internal

  pocketbase:
    build:
      context: ./pocketbase
    ports:
      - "9000:8090"
    volumes:
      - pocketbase_data:/pb_data
    networks:
      - sanctum_internal

networks:
  sanctum_internal:

volumes:
  postgres_data:
  pocketbase_data:
