package auth

import (
	"crypto/rsa"
	"encoding/base64"
	"math/big"
	"net/http"

	"github.com/labstack/echo/v4"
)

// jwkKey is the public key in JWK format.
//
// Kty: Key Type, indicating the algorithm series used by the current key. The following are three commonly used values:
//   - RSA indicates that this is a key generated by the RSA algorithm.
//   - EC indicates that this is a key generated by an ECDSA algorithm.
//   - oct indicates that this is a symmetric key.
//
// Kid: Key ID, the unique identifier of the key.
//
// Use: Public Key Use, indicating the purpose of the public key.
// The public key can be used to verify signatures (JWS) or to encrypt data (JWE). It has two possible values:
//   - sig: Verify signature.
//   - enc: Encrypt data.
//
// Alg: Algorithm, indicating the specific algorithm used by the current key, such as RSA256, etc.
// It must match the kty. e.g. kty is EC and alg is RSA256, then obviously this is a wrong JWT.
//
// Kid: Key ID, the unique identifier of the key.
// When we have multiple keys that can be used to sign the JWT,
// we can include the kid field in the JWT to indicate which key was used to issue it, so that the verifier can quickly
// find the key used to verify this JWT. Its value can be any string, so it can be a timestamp, a number, a UUID,
// or whatever, as long as it helps us distinguish between different keys.
//
// E and n are the exclusive fields of the RSA algorithm. N is the modulus of the RSA public key,
// and e is the exponent of the RSA public key.
//
// [Source]
//
// [Source]: https://www.emqx.com/en/blog/jwt-authentication-and-jwks-endpoint-in-mqtt
type jwkKey struct {
	Kty string `json:"kty"` // "RSA"
	Kid string `json:"kid"`
	Use string `json:"use"` // "sig"
	Alg string `json:"alg"` // "RS256"
	N   string `json:"n"`   // base64url(modulus)
	E   string `json:"e"`   // base64url(exponent)
}
type jwks struct {
	Keys []jwkKey `json:"keys"`
}

// rsaToJWK converts an RSA public key to a JWK entry.
func rsaToJWK(pub *rsa.PublicKey, kid string) jwkKey {
	n := base64.RawURLEncoding.EncodeToString(pub.N.Bytes())
	e := base64.RawURLEncoding.EncodeToString(big.NewInt(int64(pub.E)).Bytes())
	return jwkKey{Kty: "RSA", Kid: kid, Use: "sig", Alg: "RS256", N: n, E: e}
}

// JWKSHandler returns an Echo handler that serves one or more public keys.
// Pass ALL active/valid public keys so verifiers can handle tokens with different kids.
func JWKSHandler(pub *rsa.PublicKey, kid string) echo.HandlerFunc {
	return func(c echo.Context) error {
		return c.JSON(http.StatusOK, jwks{Keys: []jwkKey{rsaToJWK(pub, kid)}})
	}
}
