root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -gcflags='all=-N -l' -o ./tmp/main ./cmd/api"
bin = "./tmp/main"
full_bin = "dlv exec --accept-multiclient --headless --continue --listen=:4200 --api-version=2 ./tmp/main"

[misc]
clean_on_exit = true