version: '3'

dotenv: ['.env']

vars:
  DB_DRIVER: postgres
  METRICS_CONTAINER: "sanctum-metrics-1"
  DB_CONNECTION_STRING: "postgres://dev:password@localhost:5430/metrics?sslmode=disable"
  MIGRATIONS_DIR: "./internal/db/migrations"
  SQLC_CONFIG: "./internal/db/sqlc.yml"

tasks:
  migrate:create:
    desc: Create a new migration file
    interactive: true
    silent: true
    cmds:
      - |
        echo -n "Enter migration name: "
        read name
        goose -dir {{.MIGRATIONS_DIR}} create "$name" sql

  migrate:up:
    desc: Apply all available migrations
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} {{.DB_DRIVER}} "{{.DB_CONNECTION_STRING}}" up

  migrate:down:
    desc: Rollback the last applied migration
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} {{.DB_DRIVER}} "{{.DB_CONNECTION_STRING}}" down

  rebuild:
     desc: Rebuilds the GO project and restarts the debugger
     cmds:
       - docker exec {{.METRICS_CONTAINER}} bash -c 'cd scripts && ./build-and-debug.sh'

  sqlc:generate:
    desc: Generate Go code from SQL
    cmds:
      - sqlc generate -f {{.SQLC_CONFIG}}

  seed:init:
    desc: Seed admin user
    env:
      AUTH_DATABASE_URL: '{{.DB_CONNECTION_STRING}}'
    cmds:
      - go run cmd/seed/main.go