services:
  web:
    build: ./web
    volumes:
      - ./web:/web
    env_file:
      - ./web/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HOST=0.0.0.0
      - STORYBOOK_HOST=0.0.0.0
    ports:
      - "5173:5173"
      - "6006:6006"
      - "9229:9229"  # Debugger
    networks:
      - sanctum_internal

  metrics:
    build: ./backend/metrics
    volumes:
      - ./backend/metrics:/app
    ports:
      - "3000:3000"
      - "4200:4200"
    networks:
      - sanctum_internal

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metrics
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    networks:
      - sanctum_internal

networks:
  sanctum_internal:

volumes:
  postgres_data: {}